language: python
python:
    - 3.6

addons:
  sonarcloud:
    organization: "JaeguKim-github"

# cache:
#   directories:
#     - '$HOME/.sonar/cache'

# command to install dependencies
install:
  - pip install HowLongToBeat-Python-API
  - pip install nose
  - pip install codecov

# command to run tests
script:
  - nosetests HowLongToBeat-Python-API #--with-coverage
  #- coverage xml

#after_success:
#  - codecov
#  - sonar-scanner